name: 'Build docker'

on:
  workflow_call:
    secrets:
      GHCR_TOKEN:
        required: true
    inputs:
      push:
        description: 'Push the image to the registry'
        required: false
        type: boolean
        default: true
      scan:
        description: 'Scan the image with Trivy'
        required: false
        type: boolean
        default: true
      scan_severity:
        description: 'Severity of vulnerabilities to fail the build'
        required: false
        type: string
        default: 'CRITICAL,HIGH'
      scan_vuln_type:
        description: 'Type of vulnerabilities to scan'
        required: false
        type: string
        default: 'os,library'
      image_name:
        description: 'Name of the image to build'
        type: string
        required: true
      image_tag:
        description: 'Tag of the image to build'
        type: string
        required: true
      image_extra_aliases:
        description: 'Extra aliases for the image, e.g. to publish to multiple registries'
        type: string
        required: false
        default: ''
      ghcr_username:
        description: 'GitHub Container Registry username'
        type: string
        required: false
        default: ''
      ghcr_password:
        description: 'GitHub Container Registry password'
        type: string
        required: false
        default: ''
      dockerhub_username:
        description: 'Docker Hub username'
        type: string
        required: false
        default: ''
      dockerhub-password:
        description: 'Docker Hub password'
        type: string
        required: false
        default: ''

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc #v2.2.0
        with:
          registry: ghcr.io
          username: ${{ inputs.ghcr_username }}
          password: ${{ secrets.GHCR_TOKEN }}
      # - name: Login to Docker Hub
      #   if: ${{ inputs.push == 'true' }} # workaround for composite jobs not being able to pass boolean inputs
      #   uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc #v2.2.0
      #   with:
      #     username: ${{ inputs.dockerhub_username }}
      #     password: ${{ inputs.dockerhub_password }}
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
      - name: Build  Docker image
        uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 #v4.2.1
        with:
          context: .
          push: ${{ inputs.push }}
          tags: |
            ${{ inputs.image_name }}:${{ inputs.image_tag }}
            ${{ inputs.image_extra_aliases }}
          labels: |
            maintainer=AI DIAL
            org.opencontainers.image.title=${{ inputs.image_name }}
            org.opencontainers.image.version=${{ inputs.image_tag }}
            org.opencontainers.image.description=${{ inputs.image_name }}
            org.opencontainers.image.created=${{ github.event.repository.pushed_at }}
            org.opencontainers.image.licenses=Apache-2.0
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}
  
      # - name: Run Trivy vulnerability scanner
      #   if: ${{ inputs.scan == 'true' }} # workaround for composite jobs not being able to pass boolean inputs
      #   uses: aquasecurity/trivy-action@fbd16365eb88e12433951383f5e99bd901fc618f #0.12.0
      #   with:
      #     image-ref: '${{ inputs.image_name }}:${{ inputs.image_tag }}'
      #     format: 'table'
      #     exit-code: '1'
      #     vuln-type: ${{ inputs.scan_vuln_type }}
      #     severity: ${{ inputs.scan_severity }}
  