name: Run e2e-test


on:
  workflow_call:
    inputs:
      gitlab-project-id:
        default: "1843"
        description: "The ID or path of the project owned by the authenticated user."
        type: string
      gitlab-project-ref:
        default: "master"
        description: "The branch or tag to run the pipeline on."
        type: string
    secrets:
      DEPLOY_HOST:
        required: true
      DEPLOY_TRIGGER_TOKEN:
        required: true
      DEPLOY_ACCESS_TOKEN:
        required: true

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest
    concurrency: e2e-test
    environment:
      name: e2e-test
    steps:
      - id: identify
        run: |
          # use bash variable expression to get the substring
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA:0:7}" >>$GITHUB_ENV

      - name: Just echo
        run: |
          echo "debug env ${GITHUB_SHA}"
          echo "debug env2 ${GITHUB_SHA_SHORT}"

      - name: Deploy environment
        id: deploy
        uses: digital-blueprint/gitlab-pipeline-trigger-action@990eaca56dc9b9439da90dd81ab9311adce0dcce # v1.0.5
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          trigger_token: ${{ secrets.DEPLOY_TRIGGER_TOKEN }}
          access_token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
          id: ${{ inputs.gitlab-project-id }}
          ref: ${{ inputs.gitlab-project-ref }}
          variables: >
            {
              "GITHUB_APP":"${{ github.event.repository.name }}",
              "GITHUB_PR": "${{ env.GITHUB_SHA_SHORT }}"
            }
