name: Nested Reusable workflow

on:
  workflow_call:

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  second-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "NESTED aaaaaaa"
