name: Release version

on:
  workflow_call:
    secrets:
      ACTIONS_BOT_TOKEN:
        required: true

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  calculate_version:
    uses: ./.github/workflows/semantic_versioning.yml

  publish-docker:
    needs:
      - calculate_version
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/build_docker.yml
    with:
      ghcr_username: ${{ github.actor }}
      image_name: ghcr.io/${{ github.repository }}
      image_tag: ${{ needs.calculate_version.outputs.next_version }}
      push: true
      scan: true
      image_extra_aliases: |
        ${{ github.ref == 'refs/heads/development' && format('{0}/{1}:{2}', 'ghcr.io', github.repository, 'development') || ''}}
        ${{ startsWith(github.ref, 'refs/heads/release-') && needs.calculate_version.outputs.is_latest == 'true' && format('{0}/{1}:{2}', 'ghcr.io', github.repository, 'latest') || ''}}
    secrets:
      GHCR_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
    
  # generate_release_notes:
  #   uses: ./.github/workflows/generate_release_notes.yml
  #   if: github.ref =~ 'refs/heads/release-'


  # publish_tag_release:
  #   uses: ./.github/workflows/publish_tag_release.yml
  #   if: github.ref =~ 'refs/heads/release-'

