name: Reusable workflow

on:
  workflow_call:

jobs:
  first-echo:
    runs-on: ubuntu-latest
    steps:
      - name: just-echo
        run: |
          echo "reusable workflow TEST2"

  call-another-reusable:
    uses: ./.github/workflows/nested-workflow.yml
